#!/bin/bash
# Written by: M.B. Hudson (2020) malcode.net
cd
cd Bot-Lab
clear
echo "  A global Scan will be conducted and will take approx 24 hours"
echo " during the scanning stage you may press CTRL+C to skip to the "
echo " Nmap portion were the newly acquired server list will be"
echo " checked for amplification vulnerabilities. Vulnerable servers "
echo " will be saved to a file titled MemcachedMasterList.txt in "
echo " your Bot-Lab Folder"
echo "" 
echo " Bot-Lab also saves your scan progress in between sessions "
echo ""
echo ""
read -p "Press enter to continue with scan"
masscan -p11211 0.0.0.0/0 --exclude 255.255.255.255 --rate=99999999999 -oX /root/Bot-Lab/MemcachedGlobalScan.txt
clear
echo  "Extracting IPs.... "
sleep 2
grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' /root/Bot-Lab/MemcachedGlobalScan.txt > /root/Bot-Lab/MemcachedGlobalIP.txt 
sleep 2
read -p "Press enter to continue with server exploit validation"
clear
nmap -p 11211 --script memcached-info -iL /root/Bot-Lab/MemcachedGlobalIP.txt 2>&1 | tee MemcachedValid.txt 
clear
grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' /root/Bot-Lab/MemcachedValid.txt > /root/Bot-Lab/MemcachedMasterList.txt
echo ""
echo "VALIDATED SERVER LIST SAVED AT /root/Bot-Lab/MemcachedMasterList.txt"
read -p "Press enter to continue with scan"
nano /root/Bot-Lab/MemcacheMasterList.txt
