#!/bin/bash
# Written by: M.B. Hudson (2020) malcode.net
cd
cd Bot-Lab
clear
echo "  A global Scan will be conducted and will take approx 24 hours"
echo " during the scanning stage you may press CTRL+C to skip to the "
echo " Nmap portion were the newly acquired server list will be"
echo " checked for amplification vulnerabilities. Vulnerable servers "
echo " will be saved to a file titled MemcacheMasterList.txt in "
echo " your Bot-Lab Folder"
echo "" 
echo " Bot-Lab also saves your scan progress in between sessions "
echo ""
echo ""
read -p "Press enter to continue with scan"
masscan -p123 0.0.0.0/0 --exclude 255.255.255.255 --rate=99999999999 -oX /root/Bot-Lab/NTPGlobalScan.txt
clear
echo  "Extracting IPs.... "
sleep 2
grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' /root/Bot-Lab/NTPGlobalScan.txt > /root/Bot-Lab/NTPGlobalIP.txt 
sleep 2
read -p "Press enter to continue with server exploit validation"
clear
nmap -sU -pU:123 -Pn -n --max-retries=0 -iL /root/Bot-Lab/NTPGlobalIP.txt -vv 2>&1 | tee NTPValid.txt 
clear
grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' /root/Bot-Lab/NTPValid.txt > /root/Bot-Lab/NTPMasterList.txt
echo ""
echo "VALIDATED SERVER LIST SAVED AT /root/Bot-Lab/NTPMasterList.txt"
read -p "Press enter to continue with scan"
nano /root/Bot-Lab/NTPMasterList.txt
 
